# Generated by Django 4.0 on 2022-01-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_stack_over_flow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
